FROM python

WORKDIR /app


COPY . /app

CMD ["python", "rng.py"]


# docker build .
# docker run -it 
#fatemehrahimi@fatemehRahimis-MacBook-Pro python-app-starting-setup % docker run -i -t fba568f6b48c
#Please enter the min number: 34
#Please enter the max number: 56
#50
#fatemehrahim